import type { Anime } from '@/lib/types';

export const mockAnimeData: Anime[] = [
  {
    id: '1',
    slug: 'cyber-ronin',
    title: 'Cyber Ronin',
    description: 'In the neon-drenched metropolis of Neo-Kyoto, a lone cyborg samurai, a "Ronin," seeks revenge against the corrupt corporation that built him. A tale of action, betrayal, and finding humanity in a world of machines.',
    coverImageId: 'anime-1',
    heroImageId: 'hero-1',
    genres: ['Sci-Fi', 'Action', 'Cyberpunk'],
    rating: 4.8,
    year: 2024,
    status: 'Airing',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `cr-ep${i + 1}`,
      slug: `cyber-ronin-episode-${i + 1}`,
      title: `Episode ${i + 1}`,
      episodeNumber: i + 1,
      thumbnailId: `episode-thumb-${(i % 4) + 1}`,
      duration: '24m',
    })),
  },
  {
    id: '2',
    slug: 'astral-chronicles',
    title: 'Astral Chronicles',
    description: 'A young mage discovers she has the power to traverse the Astral Plane. She must master her abilities to stop a celestial cataclysm that threatens to unravel reality itself.',
    coverImageId: 'anime-2',
    heroImageId: 'hero-2',
    genres: ['Fantasy', 'Magic', 'Adventure'],
    rating: 4.5,
    year: 2023,
    status: 'Finished',
    episodes: Array.from({ length: 24 }, (_, i) => ({
      id: `ac-ep${i + 1}`,
      slug: `astral-chronicles-episode-${i + 1}`,
      title: `Chapter ${i + 1}`,
      episodeNumber: i + 1,
      thumbnailId: `episode-thumb-${(i % 4) + 1}`,
      duration: '23m',
    })),
  },
  {
    id: '3',
    slug: 'ghost-of-yokohama',
    title: 'Ghost of Yokohama',
    description: 'A detective with the ability to see ghosts must solve a series of supernatural crimes in modern-day Yokohama, partnering with a mischievous spirit from the Edo period.',
    coverImageId: 'anime-3',
    heroImageId: 'hero-3',
    genres: ['Mystery', 'Supernatural', 'Detective'],
    rating: 4.7,
    year: 2022,
    status: 'Finished',
    episodes: Array.from({ length: 12 }, (_, i) => ({
      id: `goy-ep${i + 1}`,
      slug: `ghost-of-yokohama-episode-${i + 1}`,
      title: `Case File #${i + 1}`,
      episodeNumber: i + 1,
      thumbnailId: `episode-thumb-${(i % 4) + 1}`,
      duration: '25m',
    })),
  },
  {
    id: '4',
    slug: 'mech-cadets',
    title: 'Mech Cadets',
    description: 'In a future where humanity defends against an alien threat, talented teenagers are chosen to pilot giant mechs. Follow the journey of a new recruit and her unexpected bond with her sentient robot.',
    coverImageId: 'anime-4',
    heroImageId: 'hero-4',
    genres: ['Mecha', 'Sci-Fi', 'Action'],
    rating: 4.4,
    year: 2024,
    status: 'Airing',
    episodes: Array.from({ length: 6 }, (_, i) => ({
      id: `mc-ep${i + 1}`,
      slug: `mech-cadets-episode-${i + 1}`,
      title: `Sortie ${i + 1}`,
      episodeNumber: i + 1,
      thumbnailId: `episode-thumb-${(i % 4) + 1}`,
      duration: '22m',
    })),
  },
    {
    id: '5',
    slug: 'the-last-spellbinder',
    title: 'The Last Spellbinder',
    description: 'In a world where magic is fading, a young girl discovers she is the last of the legendary Spellbinders. She embarks on a quest to restore magic before her world succumbs to a creeping technological blight.',
    coverImageId: 'anime-5',
    heroImageId: 'hero-1',
    genres: ['Fantasy', 'Adventure'],
    rating: 4.9,
    year: 2023,
    status: 'Finished',
    episodes: Array.from({ length: 18 }, (_, i) => ({
      id: `tls-ep${i + 1}`,
      slug: `the-last-spellbinder-episode-${i + 1}`,
      title: `The Fading Ember - Part ${i + 1}`,
      episodeNumber: i + 1,
      thumbnailId: `episode-thumb-${(i % 4) + 1}`,
      duration: '24m',
    })),
  },
  {
    id: '6',
    slug: 'tokyo-neon-hustle',
    title: 'Tokyo Neon Hustle',
    description: 'A slice-of-life comedy about a group of friends trying to make it big in the bustling, competitive world of Tokyo\'s underground music scene. Juggling part-time jobs, rehearsals, and rival bands, they chase their dreams one gig at a time.',
    coverImageId: 'anime-6',
    heroImageId: 'hero-2',
    genres: ['Slice of Life', 'Comedy', 'Music'],
    rating: 4.6,
    year: 2024,
    status: 'Airing',
    episodes: Array.from({ length: 8 }, (_, i) => ({
      id: `tnh-ep${i + 1}`,
      slug: `tokyo-neon-hustle-episode-${i + 1}`,
      title: `Sound Check #${i + 1}`,
      episodeNumber: i + 1,
      thumbnailId: `episode-thumb-${(i % 4) + 1}`,
      duration: '24m',
    })),
  },
];

export const genres = [...new Set(mockAnimeData.flatMap(anime => anime.genres))];
